import type { EventType } from "./metrics";

/**
 * Click vs conversion — CLAUDE.md §15 makes this distinction mandatory.
 *
 * The platform can observe three different things, and they are not equally
 * trustworthy:
 *
 *   REACH      someone arrived — tap, scan, view
 *   ENGAGEMENT someone pressed something — click
 *   CONFIRMED  something demonstrably completed — download, lead
 *
 * Only the third is a conversion in any defensible sense. A click on a Google
 * review button tells us the link was followed and nothing whatsoever about
 * whether a review was written; the browser leaves our origin and never comes
 * back to report. `download` and `lead` are different in kind: the vCard is
 * generated by our own code, and the lead is written by our own server.
 */
export const REACH_EVENTS: EventType[] = ["tap", "scan", "view"];
export const ENGAGEMENT_EVENTS: EventType[] = ["click"];
export const CONFIRMED_EVENTS: EventType[] = ["download", "lead"];

export type AnalyticsScope = "account" | "page";

export type Analytics = {
  days: number;
  scope: AnalyticsScope;
  pages: number;
  totals: Partial<Record<EventType, number>>;
  previous: Partial<Record<EventType, number>>;
  leads: number;
  previous_leads: number;
  daily: {
    date: string;
    tap: number;
    scan: number;
    view: number;
    click: number;
    download: number;
    lead: number;
  }[];
  by_source: { source: string; count: number }[];
  by_device: { id: string; label: string | null; token: string; count: number }[];
  by_country: { country: string; count: number }[];
  by_hour: { hour: number; count: number }[];
  top_blocks: { label: string; type: string; count: number }[];
  top_pages: { id: string; slug: string; title: string | null; events: number }[];
};

const sum = (totals: Partial<Record<EventType, number>>, keys: EventType[]) =>
  keys.reduce((acc, k) => acc + (totals[k] ?? 0), 0);

export function reachCount(totals: Partial<Record<EventType, number>>): number {
  return sum(totals, REACH_EVENTS);
}
export function engagementCount(totals: Partial<Record<EventType, number>>): number {
  return sum(totals, ENGAGEMENT_EVENTS);
}
export function confirmedCount(totals: Partial<Record<EventType, number>>): number {
  return sum(totals, CONFIRMED_EVENTS);
}

/**
 * Opens of an actual page — the only defensible denominator for a rate.
 *
 * `tap` is excluded deliberately. An NFC tap on a smart page records BOTH a tap
 * (at /t/<token>) and a view (when the page renders), so including taps would
 * count one visit twice; and a redirect-mode link records a tap with no page to
 * act on at all. Views plus QR scans is the set of visits that could possibly
 * have produced a click.
 */
export function pageOpens(totals: Partial<Record<EventType, number>>): number {
  return (totals.view ?? 0) + (totals.scan ?? 0);
}

/**
 * Share of page opens that produced something we can prove happened.
 *
 * Returns undefined when there is nothing to divide by — a rate out of zero is
 * not 0%, it is unknown, and the same rule that governs percentChange applies
 * here (§30.7).
 */
export function confirmedRate(
  totals: Partial<Record<EventType, number>>,
): number | undefined {
  const opens = pageOpens(totals);
  if (opens === 0) return undefined;
  return (confirmedCount(totals) / opens) * 100;
}

/** Share of page opens where a visitor pressed at least one action. */
export function engagementRate(
  totals: Partial<Record<EventType, number>>,
): number | undefined {
  const opens = pageOpens(totals);
  if (opens === 0) return undefined;
  return (engagementCount(totals) / opens) * 100;
}

const SOURCE_LABELS: Record<string, string> = {
  nfc: "NFC card",
  qr: "QR code",
  direct: "Direct link",
  web: "Web",
  unknown: "Unknown",
};

/**
 * Events recorded before migration 0010 carry no source. They are reported as
 * "Not recorded" rather than folded into "Direct", which would silently
 * overstate one channel.
 */
export function sourceLabel(source: string): string {
  if (source === "unknown") return "Not recorded";
  return SOURCE_LABELS[source] ?? source;
}

/** ISO-3166 alpha-2 to a country name, via the platform's own data — no dependency. */
export function countryLabel(code: string): string {
  if (!code || code === "unknown") return "Unknown";
  try {
    const display = new Intl.DisplayNames(["en"], { type: "region" });
    return display.of(code.toUpperCase()) ?? code;
  } catch {
    return code;
  }
}

/** "2 PM" — hour labels for the time-of-day chart. */
export function hourLabel(hour: number): string {
  if (hour === 0) return "12 AM";
  if (hour === 12) return "12 PM";
  return hour < 12 ? `${hour} AM` : `${hour - 12} PM`;
}

/**
 * Busiest stretch of the day, as a fact rather than a recommendation.
 *
 * Returns the best three-hour window and what share of activity falls in it.
 * Deliberately does NOT phrase this as advice ("ask for reviews at 2–4pm") —
 * that is an inference about customer behaviour the data does not support, and
 * it belongs to UI-10 if anywhere.
 */
export function busiestWindow(
  byHour: { hour: number; count: number }[],
): { startHour: number; endHour: number; count: number; share: number } | undefined {
  if (byHour.length === 0) return undefined;
  const counts = new Array(24).fill(0) as number[];
  for (const { hour, count } of byHour) {
    if (hour >= 0 && hour < 24) counts[hour] = count;
  }
  const total = counts.reduce((a, b) => a + b, 0);
  if (total === 0) return undefined;

  let bestStart = 0;
  let best = -1;
  for (let start = 0; start <= 21; start++) {
    const windowCount = counts[start] + counts[start + 1] + counts[start + 2];
    if (windowCount > best) {
      best = windowCount;
      bestStart = start;
    }
  }
  return {
    startHour: bestStart,
    endHour: bestStart + 3,
    count: best,
    share: (best / total) * 100,
  };
}
