// Slugs that must never be handed to a customer because they collide with
// platform routes, are misleading, or are reserved for future use.
export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  // platform / routing
  "api",
  "app",
  "admin",
  "auth",
  "login",
  "logout",
  "signup",
  "signin",
  "register",
  "dashboard",
  "account",
  "accounts",
  "settings",
  "billing",
  "subscribe",
  "subscription",
  "profile",
  "profiles",
  "onboarding",
  // Reserved in UI-1 (D-013): `/[slug]` is a root catch-all, so every name the
  // product might one day route to must be withheld from customers BEFORE
  // launch. Free now; breaking once someone owns one.
  "analytics",
  "insights",
  "customers",
  "leads",
  "contacts",
  "devices",
  "nfc",
  "tags",
  "cards",
  "qr",
  "team",
  "members",
  "notifications",
  "integrations",
  "print", // /print/qr — printable QR sheets (UI-6)
  "static",
  "assets",
  "public",
  "_next",
  "www",
  "mail",
  "ftp",
  // brand / marketing
  "taptap",
  "hornbill",
  "hornbilltech",
  "home",
  "about",
  "pricing",
  "contact",
  "support",
  "help",
  "terms",
  "privacy",
  "legal",
  "blog",
  "docs",
  "status",
  // safety
  "null",
  "undefined",
  "root",
  "system",
  "t", // reserved for NFC tag token routes: /t/<token>
]);
