// Slugs that must never be handed to a customer because they collide with
// platform routes, are misleading, or are reserved for future use.
export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  // platform / routing
  "api",
  "app",
  "admin",
  "auth",
  "login",
  "logout",
  "signup",
  "signin",
  "register",
  "dashboard",
  "account",
  "accounts",
  "settings",
  "billing",
  "subscribe",
  "subscription",
  "profile",
  "profiles",
  "onboarding",
  "static",
  "assets",
  "public",
  "_next",
  "www",
  "mail",
  "ftp",
  // brand / marketing
  "taptap",
  "hornbill",
  "hornbilltech",
  "home",
  "about",
  "pricing",
  "contact",
  "support",
  "help",
  "terms",
  "privacy",
  "legal",
  "blog",
  "docs",
  "status",
  // safety
  "null",
  "undefined",
  "root",
  "system",
]);
