-- Hornbill TapTap — Sprint UI-10: Insights
--
-- This migration supplies FACTS ONLY. Every threshold and every sentence lives
-- in lib/insights.ts, so the rules are unit-testable without a database and a
-- reviewer can read what the product will claim in one file.
--
-- Nothing here infers anything. "Which action gets the most clicks" is a count;
-- "you should move WhatsApp up" is a rule applied to that count, and the UI
-- shows the count alongside the advice so an owner can disagree with it.

-- ---------------------------------------------------------------------------
-- Dismissals
-- ---------------------------------------------------------------------------
-- Without these the panel becomes noise an owner cannot silence, and a
-- suggestion they have deliberately rejected keeps reappearing. Keys are
-- generated by the rule engine and are stable for the same finding.
create table if not exists public.insight_dismissals (
  account_id  uuid not null references public.accounts(id) on delete cascade,
  insight_key text not null,
  dismissed_at timestamptz not null default now(),
  primary key (account_id, insight_key)
);

alter table public.insight_dismissals enable row level security;

drop policy if exists insight_dismissals_all_own on public.insight_dismissals;
create policy insight_dismissals_all_own on public.insight_dismissals
  for all using (
    account_id in (select account_id from public.profiles where id = auth.uid())
  ) with check (
    account_id in (select account_id from public.profiles where id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- Raw inputs for the rule engine
-- ---------------------------------------------------------------------------
create or replace function public.get_insight_inputs(p_days int default 30)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with my_account as (
    select account_id from public.profiles where id = auth.uid()
  ),
  bounds as (
    select now() - make_interval(days => p_days) as cur_from
  ),
  my_pages as (
    select id, slug, title, status, is_active, config, published_content
    from public.smart_pages
    where account_id in (select account_id from my_account)
  ),
  cur as (
    select e.*
    from public.events e, bounds b
    where e.smart_page_id in (select id from my_pages) and e.ts >= b.cur_from
  ),
  page_stats as (
    select
      p.id,
      count(e.id) filter (where e.type in ('view', 'scan'))::int      as opens,
      count(e.id) filter (where e.type = 'click')::int                as clicks,
      count(e.id) filter (where e.type in ('download', 'lead'))::int  as confirmed
    from my_pages p
    left join cur e on e.smart_page_id = p.id
    group by p.id
  ),
  -- What the PUBLIC actually sees, read from the published snapshot rather than
  -- the editable draft: a dead button only matters once it is live, and an
  -- owner who fixed the draft without publishing has not fixed it yet.
  published_actions as (
    select
      p.id as page_id,
      (a.value ->> 'id')::uuid                as link_id,
      a.value ->> 'label'                     as label,
      a.value ->> 'type'                      as type,
      coalesce((a.value ->> 'sort_order')::int, 0) as sort_order,
      coalesce(nullif(trim(a.value ->> 'value'), ''), null) as value
    from my_pages p
    cross join lateral jsonb_array_elements(
      coalesce(p.published_content -> 'links', '[]'::jsonb)
    ) as a
    where p.status = 'published'
  )
  select jsonb_build_object(
    'days', p_days,

    'pages', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'slug', p.slug,
        'title', p.title,
        'status', p.status,
        'is_active', p.is_active,
        'lead_form_enabled', coalesce((p.config -> 'leadForm' ->> 'enabled')::boolean, false),
        'opens', s.opens,
        'clicks', s.clicks,
        'confirmed', s.confirmed,
        'published_action_count', (
          select count(*)::int from published_actions pa where pa.page_id = p.id
        ),
        'dead_action_count', (
          -- An action with no destination renders as a button that does
          -- nothing. contact and mpesa act in-page and need no value.
          select count(*)::int from published_actions pa
          where pa.page_id = p.id
            and pa.value is null
            and pa.type not in ('contact', 'mpesa')
        )
      ))
      from my_pages p join page_stats s on s.id = p.id
    ), '[]'::jsonb),

    -- Clicks per published action, carrying the order it appears in.
    'actions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'page_id', pa.page_id,
        'link_id', pa.link_id,
        'label', pa.label,
        'type', pa.type,
        'sort_order', pa.sort_order,
        'clicks', (
          select count(*)::int from cur e
          where e.type = 'click' and e.link_id = pa.link_id
        )
      ))
      from published_actions pa
    ), '[]'::jsonb),

    'devices', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id,
        'label', t.label,
        'token', t.token,
        'status', t.status,
        'claimed_at', t.claimed_at,
        'smart_page_id', t.smart_page_id,
        'taps', (
          select count(*)::int from cur e where e.tag_id = t.id
        )
      ))
      from public.nfc_tags t
      where t.account_id in (select account_id from my_account)
    ), '[]'::jsonb),

    'leads', (
      select jsonb_build_object(
        'new_count', count(*) filter (where l.status = 'new')::int,
        'stale_new_count', count(*) filter (
          where l.status = 'new' and l.created_at < now() - interval '7 days'
        )::int,
        'oldest_new_at', min(l.created_at) filter (where l.status = 'new')
      )
      from public.leads l
      where l.smart_page_id in (select id from my_pages)
    ),

    'dismissed', coalesce((
      select jsonb_agg(insight_key)
      from public.insight_dismissals
      where account_id in (select account_id from my_account)
    ), '[]'::jsonb)
  );
$$;

grant execute on function public.get_insight_inputs(int) to authenticated;
