"use server";

import { revalidatePath } from "next/cache";
import { createServerSupabase } from "@/lib/supabase/server";

export type DismissResult = { error?: string };

/**
 * Hides a finding the owner has decided not to act on.
 *
 * Without this the panel nags: a suggestion deliberately rejected would return
 * every time the page loads. Keys are generated by the rule engine and stay
 * stable for the same finding, so a dismissal survives recomputation.
 */
export async function dismissInsightAction(key: string): Promise<DismissResult> {
  if (!key || key.length > 200) return { error: "Invalid insight." };

  const supabase = await createServerSupabase();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  const { data: profile } = await supabase
    .from("profiles")
    .select("account_id")
    .eq("id", user.id)
    .single();
  if (!profile) return { error: "No account found." };

  // The account id comes from the session, never from the client.
  const { error } = await supabase
    .from("insight_dismissals")
    .upsert(
      { account_id: profile.account_id, insight_key: key },
      { onConflict: "account_id,insight_key" },
    );
  if (error) return { error: error.message };

  revalidatePath("/dashboard");
  return {};
}

/** Brings dismissed findings back — an owner may change their mind. */
export async function restoreInsightsAction(): Promise<DismissResult> {
  const supabase = await createServerSupabase();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  const { data: profile } = await supabase
    .from("profiles")
    .select("account_id")
    .eq("id", user.id)
    .single();
  if (!profile) return { error: "No account found." };

  const { error } = await supabase
    .from("insight_dismissals")
    .delete()
    .eq("account_id", profile.account_id);
  if (error) return { error: error.message };

  revalidatePath("/dashboard");
  return {};
}
